default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: vsm_dev

test:
  <<: *default
  database: vsm_test

production:
  <<: *default
  database: vsm_prod
